config/routes.rb
Rails.application.routes.draw do
  root   'profiles#index'
  get    'edit',   to: 'profiles#edit'
  post   'edit',   to: 'profiles#update'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  namespace :zemoga_portfolio_api, defaults: {format: :json} do
      get  '/user_info',        to: 'profiles#index'
      post '/modify_user_info', to: 'profiles#update'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :image_url, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { username.downcase! }

  validates :username, presence: true,
                       length:   { maximum: 50 }

  has_secure_password
  validates :password, presence: true,
                       allow_nil: true,
                       length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:index, :edit, :update]
  before_action :authenticate_user!, only: [:edit, :update]

  def index
    @timeline = TwitterManager::TweetReader.call(@profile.twitter_username, 5)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      flash[:success] = 'the portfolio has been updated successfully'
      redirect_to root_path
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = Profile.first
    end

    def profile_params
      params.require(:profile)
            .permit(:name, :description, :image_url, :twitter_username)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/zemoga_portfolio_api/profiles_controller.rb
class ZemogaPortfolioApi::ProfilesController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    render json: Profile.first
  end

  def update
    profile = Profile.first
    if profile.update(profile_params)
      render json: profile
    else
      render json: { errors: profile.errors }, status: 422
    end
  end

  private
    def profile_params
      params.require(:profile)
            .permit(:name, :description, :image_url, :twitter_username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def authenticate_user!
    redirect_to login_path unless logged_in?
  end
end

app/views/layouts/_alerts.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-4 col-md-8 col-md-offset-2">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <strong>Jon's</strong> Portfolio
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="nav-item <%= 'current' if current_page?(edit_path) %>">
              <%= link_to "Edit", edit_path %>
            </li>
            <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
          <% else %>
            <li class="nav-item <%= 'current' if current_page?(login_path) %>">
              <%= link_to "Sign In", login_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jon's Portfolio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<% if profile.errors.full_messages.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h2><%= title %></h2>
<%= form_with scope: :profile, url: edit_path, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name, class: "form-control", placeholder: "Jhon Doe" %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Description:' %>
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "something interesting about you" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url, 'Image URL:' %>
    <%= f.url_field :image_url, class: "form-control", placeholder: "https://images.com/profile.png" %>
  </div>

  <div class="form-group">
    <%= f.label :twitter_username, 'Twitter Username:' %>
    <div class="input-group">
      <div class="input-group-addon">@</div>
      <%= f.text_field :twitter_username, class: "form-control", placeholder: "username" %>
    </div>
  </div>
  <%= f.submit action, class: "btn btn-primary"%>
  <%= link_to "Cancel", root_path, class: "btn btn-default" %>

<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
    <%= render 'form', profile: @profile, title: "Edit Portfolio", action: "Update" %>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
    <div class="profile">
      <div class="col-md-4">
        <a href="<%= @profile.image_url %>">
          <img src="<%= @profile.image_url %>" alt="profile picture" class="img-thumbnail">
        </a>
        <p></p>
        <div class="twt-wrapper">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><a href="https://twitter.com/<%= @profile.twitter_username %>"><%= @profile.twitter_username %>'s Timeline</a></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-12">
                  <ul class="media-list">
                    <% @timeline.each do |tweet| %>
                      <li class="media">
                        <a href="#" class="pull-left">
                          <img src="<%= image_path(tweet.user.profile_image_url_https.to_s.gsub('_normal','')) %>" alt="" class="img-circle">
                        </a>
                        <div class="media-body">
                          <span class="text-muted pull-right">
                            <small class="text-muted"><%= time_ago_in_words(tweet.created_at) %></small>
                          </span>
                          <strong class="text-success"><%= "@#{tweet.user.screen_name}" %></strong>
                          <p class="text-muted"><%= tweet.text %></p>
                          <p class="text-muted pull-right">
                            <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> <%= tweet.retweet_count %>
                            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> <%= tweet.favorite_count %>
                          </p>
                        </div>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <h2><%= @profile.name %></h2>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">My Work Experience</h3>
          </div>
          <div class="panel-body">
            <%= @profile.description %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>